# Generated by Django 5.0.4 on 2024-09-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("actor", "actor"),
                    ("director", "director"),
                    ("writer", "writer"),
                ],
                default="actor",
                max_length=10,
                verbose_name="role",
            ),
        ),
    ]
